version: '3.1'
services:
  kommonitor-processing-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8086:8086"
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - KOMMONITOR_DATA_MANAGEMENT_HOST=localhost
     - KOMMONITOR_DATA_MANAGEMENT_PORT=8085
     - KOMMONITOR_DATA_MANAGEMENT_BASEPATH=/rest/v1
  redis:
    image: redis:alpine
