version: '3.1'
services:
  kommonitor-processing-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8086:8086"
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
  redis:
    image: redis:alpine
