version: '2.1'

networks:
  kommonitor:
      name: kommonitor-network

services:
  kommonitor-processing-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8086:8086"
    networks:
     - kommonitor
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     - redis
    env_file:
    - processing-engine.env
  redis:
    image: redis:alpine
    networks:
     - kommonitor
