version: '2.1'

networks:
  kommonitor:
      name: kommonitor-network

services:
  kommonitor-processing-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8086:8086"
    networks:
     - kommonitor
    volumes:
     - .:/code
     - /code/node_modules
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - KOMMONITOR_DATA_MANAGEMENT_HOST=kommonitor-data-management-api
     - KOMMONITOR_DATA_MANAGEMENT_PORT=8085
     - KOMMONITOR_DATA_MANAGEMENT_BASEPATH=/rest/v1
  redis:
    image: redis:alpine
    networks:
     - kommonitor
